class CountryCode {
  final String name;
  final String dialCode;
  final String flag;

  const CountryCode(this.name, this.dialCode, this.flag);
}

const List<CountryCode> countryCodes = [
  CountryCode('Indonesia', '+62', '🇮🇩'),
  CountryCode('Malaysia', '+60', '🇲🇾'),
  CountryCode('Singapore', '+65', '🇸🇬'),
  CountryCode('Brunei', '+673', '🇧🇳'),
  CountryCode('Philippines', '+63', '🇵🇭'),
  CountryCode('Thailand', '+66', '🇹🇭'),
  CountryCode('Vietnam', '+84', '🇻🇳'),
  CountryCode('Myanmar', '+95', '🇲🇲'),
  CountryCode('Cambodia', '+855', '🇰🇭'),
  CountryCode('Laos', '+856', '🇱🇦'),
  CountryCode('Timor-Leste', '+670', '🇹🇱'),
  CountryCode('United States', '+1', '🇺🇸'),
  CountryCode('United Kingdom', '+44', '🇬🇧'),
  CountryCode('Australia', '+61', '🇦🇺'),
  CountryCode('Japan', '+81', '🇯🇵'),
  CountryCode('South Korea', '+82', '🇰🇷'),
  CountryCode('China', '+86', '🇨🇳'),
  CountryCode('Taiwan', '+886', '🇹🇼'),
  CountryCode('Hong Kong', '+852', '🇭🇰'),
  CountryCode('India', '+91', '🇮🇳'),
  CountryCode('Pakistan', '+92', '🇵🇰'),
  CountryCode('Bangladesh', '+880', '🇧🇩'),
  CountryCode('Sri Lanka', '+94', '🇱🇰'),
  CountryCode('Nepal', '+977', '🇳🇵'),
  CountryCode('Afghanistan', '+93', '🇦🇫'),
  CountryCode('Saudi Arabia', '+966', '🇸🇦'),
  CountryCode('United Arab Emirates', '+971', '🇦🇪'),
  CountryCode('Qatar', '+974', '🇶🇦'),
  CountryCode('Kuwait', '+965', '🇰🇼'),
  CountryCode('Oman', '+968', '🇴🇲'),
  CountryCode('Bahrain', '+973', '🇧🇭'),
  CountryCode('Turkey', '+90', '🇹🇷'),
  CountryCode('Netherlands', '+31', '🇳🇱'),
  CountryCode('Germany', '+49', '🇩🇪'),
  CountryCode('France', '+33', '🇫🇷'),
  CountryCode('Italy', '+39', '🇮🇹'),
  CountryCode('Spain', '+34', '🇪🇸'),
  CountryCode('Portugal', '+351', '🇵🇹'),
  CountryCode('Switzerland', '+41', '🇨🇭'),
  CountryCode('Sweden', '+46', '🇸🇪'),
  CountryCode('Norway', '+47', '🇳🇴'),
  CountryCode('Denmark', '+45', '🇩🇰'),
  CountryCode('Finland', '+358', '🇫🇮'),
  CountryCode('Russia', '+7', '🇷🇺'),
  CountryCode('Poland', '+48', '🇵🇱'),
  CountryCode('Ukraine', '+380', '🇺🇦'),
  CountryCode('Egypt', '+20', '🇪🇬'),
  CountryCode('South Africa', '+27', '🇿🇦'),
  CountryCode('Nigeria', '+234', '🇳🇬'),
  CountryCode('Kenya', '+254', '🇰🇪'),
  CountryCode('Morocco', '+212', '🇲🇦'),
  CountryCode('Tunisia', '+216', '🇹🇳'),
  CountryCode('Brazil', '+55', '🇧🇷'),
  CountryCode('Argentina', '+54', '🇦🇷'),
  CountryCode('Mexico', '+52', '🇲🇽'),
  CountryCode('Canada', '+1', '🇨🇦'),
  CountryCode('New Zealand', '+64', '🇳🇿'),
];
