// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-nKM5RfstmvGF0fo2IrWiTtA-G5_yv4I',
    appId: '1:125956093579:web:730e2b015e7091b4c3868e',
    messagingSenderId: '125956093579',
    projectId: 'wedding-flower-decorasi',
    authDomain: 'wedding-flower-decorasi.firebaseapp.com',
    databaseURL: 'https://wedding-flower-decorasi-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-flower-decorasi.firebasestorage.app',
    measurementId: 'G-Y6XCQQ5CCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1o1LaFuIcGTOQrpyMplqbEhPntnKwPFo',
    appId: '1:125956093579:android:241e27bb44b40b54c3868e',
    messagingSenderId: '125956093579',
    projectId: 'wedding-flower-decorasi',
    databaseURL: 'https://wedding-flower-decorasi-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-flower-decorasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF1K7K-c1iveCJCqCr-secBxSQntWzaTE',
    appId: '1:125956093579:ios:d7874cdfc91a4986c3868e',
    messagingSenderId: '125956093579',
    projectId: 'wedding-flower-decorasi',
    databaseURL: 'https://wedding-flower-decorasi-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-flower-decorasi.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF1K7K-c1iveCJCqCr-secBxSQntWzaTE',
    appId: '1:125956093579:ios:d7874cdfc91a4986c3868e',
    messagingSenderId: '125956093579',
    projectId: 'wedding-flower-decorasi',
    databaseURL: 'https://wedding-flower-decorasi-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-flower-decorasi.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-nKM5RfstmvGF0fo2IrWiTtA-G5_yv4I',
    appId: '1:125956093579:web:1dac6f9211f4ffc8c3868e',
    messagingSenderId: '125956093579',
    projectId: 'wedding-flower-decorasi',
    authDomain: 'wedding-flower-decorasi.firebaseapp.com',
    databaseURL: 'https://wedding-flower-decorasi-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-flower-decorasi.firebasestorage.app',
    measurementId: 'G-LSHDJ2NR1P',
  );
}
